### ISSUE TITLE
We should describe looping

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/simple-loops#12]
I find it a bit odd that our README content does not actually describe to the user what loops are all about, or how to use them with the various loop syntax. Instead we seem to be relying on user knowing that they need to follow the links we provide to Ruby docs or Googling to figure out how to write correct syntax to solve the lab. Why not flesh this out completely in the lab content itself?

**Comment by AnnJohn** [comment]
covered in a previous readme now
