### ISSUE TITLE
Not tracking that I ran the lab locally

### ISSUE THREAD

**Issue by dchome** [learn-co-curriculum/simple-loops#15]
Learn.co is incorrectly showing that I haven't run the lab locally. It's still letting me access the next lab, I assume because I pushed the completed lab to GitHub and submitted a pull request, but it's not showing the lab as complete in Learn.  At first, I wasn't able to progress to the next lab, but after refreshing the page I was able to.

When I first ran the learn command on the lab, I had left out the add-and-assignment operator for the counter in the until loop, so I ended up in an infinite loop that crashed my terminal.

**Comment by snags88** [comment]
this has been fixed on the last commit to master. Issue was curly braces causing exception in json parsing
