### ISSUE TITLE
Website won't recognize build

### ISSUE THREAD

**Issue by susanlovaglio** [learn-co-curriculum/simple-loops#17]
I'm having trouble getting any of my builds to be recognized in Simple Loops. It's already passed the test, I've submitted the pull request and the app has moved into the next lesson showing this one as completed. But the web site isn't changing. How can I fix this?
![screen shot 2015-11-22 at 7 38 24 pm](https://cloud.githubusercontent.com/assets/15805090/11328065/a67d87d6-9150-11e5-9ecd-9b91833b5bf9.png)

**Comment by snags88** [comment]
this has been fixed on the last commit to master. Issue was curly braces causing exception in json parsing
