### ISSUE TITLE
Local build

### ISSUE THREAD

**Issue by jayzee** [learn-co-curriculum/simple-loops#18]
My local build is passing all examples in my terminal with 0 failures but the learn page is not updating that my local build has passed.

**Comment by AnnJohn** [comment]
Hi @jayzee this is an engineering issue, so if you could file a bug report that would be great. Thanks!

**Comment by jayzee** [comment]
where do i file an engineering bug report?

**Comment by AnnJohn** [comment]
Hi @jayzee if you hover over your photo image in Learn, a menu will pop up and you'll see the Report a Bug option there. Thanks!

**Comment by jayzee** [comment]
thanks.
