### ISSUE TITLE
There may be a problem with the lesson

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/simple-loops#21]
See my screenshot--the code obviously wasn't right (for whatever reason), but I passed the lab (the lights all turned green on the lesson page). 
![test](https://cloud.githubusercontent.com/assets/16111829/12426921/6344bcc8-beaa-11e5-89c7-0493356d707d.png)

**Comment by AnnJohn** [comment]
thanks for raising this issue. When you ran your tests, where you getting failures and still had the green lights. Or were the tests all passing as well?

**Comment by CodeByLine** [comment]
This has happened a few times when I accidentally used the up-arrow to bring up a previously used command. I meant to do "learn", but called up "learn submit"--that's how I accidentally discovered this.

**Comment by AnnJohn** [comment]
Got it. Yes, "learn" will run the tests. But "learn submit" will make a pull request and the green lights will appear.

**Comment by CodeByLine** [comment]
This happened in Nitrous. When I went back to the lesson page,  "your pull request" light had already turned green, though the "test" light was still red.

**Comment by AnnJohn** [comment]
Yup, that's because the pull request was made (green light), but the tests weren't passing (red light).

**Comment by CodeByLine** [comment]
Got it.
