### ISSUE TITLE
Not Submitting

### ISSUE THREAD

**Issue by MahmoudAgamy** [learn-co-curriculum/simple-loops#22]
passed the tests but not submitting

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).


If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.
