### ISSUE TITLE
Instructions mention Sublime

### ISSUE THREAD

**Issue by nmala** [learn-co-curriculum/simple-loops#23]
Noticed that the instructions for the lab mention Sublime, even though the whole environment set up was based on Atom. Just bringing this up as a suggested fix.

**Comment by maxwellbenton** [comment]
Hi @rossmawd,

Thank you for spotting this and providing feedback. We've removed the reference to Sublime to resolve this issue and are in the process of updating this section of content in general. Thank you for your feedback and contributions!
